const data = [
  {
    name: "Ben Martin Men's Classic Collar Slim Fit Cotton Casual Full Sleeve Shirt",
    newPrice: 474,
    oldPrice: 2499,
    description:
      "Closure :- Button , Sleeve Type :- Long Sleeve , Occasion :- Casual , Pocket :- 1 Pocket Wash Care: Hand/Machine wash , Origin :- Made in INDIA, This men's Shirt is made with 100% pre-shrunk and pill-resistant cotton. High quality, very Comfortable. Still perfect fit even after the wash.Disclaimer :- Kindly refer to the size chart (Also In Images) for fitting measurement.Pattern Type: Solid",
    rating: 4,
    category: "men",
    categoryNo: 1,
    productId: 1,
    bought: 100,
  },
  {
    name: "U-TURN Men's Cotton Solid Formal/Semi Formal Shirt",
    newPrice: 378,
    oldPrice: 1599,
    description:
      "Care Instructions: Hand Wash or Machine Wash onlyPremium Shirt, extremely soft finish and rich lookStylish Full Sleeves Printed Stiped Casual/Formal Shirtshirt for men || casual shirt for men || men stylish shirt || men Printed ShirtStyle - Enhance your look by wearing this Casual Stylish Men's shirt, Team it with a pair of tapered denims Or Solid Chinos and Loafers for a fun Smart Casual look",
    rating: 4,
    category: "men",
    categoryNo: 2,
    productId: 2,
    bought: 200,
  },
  {
    name: "VOXATI Men's Denim Short Length Jacket",
    newPrice: 990,
    oldPrice: 2599,
    description:
      "Material composition Denim Style Jacket Fit type Slim Length Short Length Neckstyle Collared Neck Care instructionsMild Wash Country of Origin India Jackets Comfort Fit VOXATI Casual Party Wear Gentle Wash",
    rating: 4,
    category: "men",
    categoryNo: 3,
    productId: 3,
    bought: 300,
  },
  {
    name: "Krystle Slim Fit Dori Zipper Cotton Slim fit Cargo Pant (Dark Green)",
    newPrice: 1599,
    oldPrice: 1799,
    description:
      "PREMIUM CARGO STYLE. Made with premium materials for comfort, this classic cargo pant takes you from the workplace and the outdoors, to everyday casual wear.RELAXED STRAIGHT LEG FIT. These premium cargo pants sit at the natural waist with a relaxed seat and thigh. Finished with a roomy straight leg cut, these cargo pants will keep you comfortable all day.MAXIMUM STORAGE. Equipped with (8) pockets for maximum storage capacity. (4) cargo flap pockets, (2) slash pockets, and (2) back pockets with flaps - great for storing cell phones, wallets, tools, and other items.; Elastic with Drawstring closure Please choose a right size while placing an order. The size of the trouser is based on the waist size for example: if one wears trousers of waist size 32 inches then please choose size 34. You can also write to us for assistance using ",
    rating: 4,
    category: "men",
    categoryNo: 4,
    productId: 4,
    bought: 400,
  },
  {
    name: "MONTREZ Full Sleeve Men Denim Jacket",
    newPrice: 1110,
    oldPrice: 2220,
    description:
      "Fit Type: Regular Fit Full Sleeve Denim Men Jacket Length:Regular; Fabric:Denim; Closure:Button Size Name: Xl; Collar Style: Button Down; Age Range Description: Adult Sleeve Type: Long Sleeve",
    rating: 4,
    category: "men",
    categoryNo: 5,
    productId: 5,
    bought: 500,
  },
  {
    name: "rytras Women's Floral Printed Cotton Top",
    newPrice: 800,
    oldPrice: 2000,
    description:
      "Fabric: Cotton Wash Care: Machine Wash Neck: Mandarin Collar Style: Long Top Color: Blue",
    rating: 4,
    category: "women",
    categoryNo: 1,
    productId: 6,
    bought: 600,
  },
  {
    name: "Fashion Dream Women Top",
    newPrice: 555,
    oldPrice: 200,
    description:
      "Fabric: Cotton, Fit Type: Regular Fit Top Length: Hip Length, Style: Tunic Neck style: Mandarin Collar, Sleeve Style: ¾ th Regular Sleeve Pattern: Stripe Printed Wash care: Hand Wash, Regular Machine Wash, Do Not Bleach",
    rating: 4,
    category: "women",
    categoryNo: 2,
    productId: 7,
    bought: 700,
  },
  {
    name: "Women's 3/4 Sleeves Mandarin Neck Solid Rayon Casual Tops for Ladies",
    newPrice: 990,
    oldPrice: 1110,
    description:
      "Fabric Types : Rayon Fit Type: Regular Fit Top Size Chart: S to 2XL Sleeve Type: 3/4 Sleeve Item Length Description: Mid-Thigh Length Age Range Description: Adult Design Name: Solid Neck: Mandarin Neck Top Fabric: 100% Rayon This classic short Top is a must have for your wardrobe. This is perfect for any occasion from a casual outing to regular office wear",
    rating: 4,
    category: "women",
    categoryNo: 3,
    productId: 8,
    bought: 800,
  },
  {
    name: "feranoid Women Cotton Blend Angrakha kurti",
    newPrice: 1020,
    oldPrice: 2220,
    description: "feranoid Women Cotton Blend Angrakha kurti",
    rating: 4,
    category: "women",
    categoryNo: 4,
    productId: 9,
    bought: 900,
  },
  {
    name: "Meesan Women's Beautiful Cotton Printed Smart Casual Tunics for Office & Casual Wear",
    newPrice: 980,
    oldPrice: 1190,
    description:
      "color:- Grey|| Fabric : - Tunic : Cotton Sleeves : Three Quarter Sleeves || Sleeve Styling : Regular Sleeves || Neck : V-Neck The tunic is available from S-XXXL for everyone. It’s a perfect tunic for teen girls, mom, wife, friends & perfect for pregnant women also. Makes you more fashionable and gorgeous. Occasion : Perfect for everyone to wear this tunic top with leggings, skinny jeans, Capri, Yoga Pants with boots, sneakers or heels. Age Range Description: Adult|| Uses : Casual, Ethnic, office || Care Description : Machine Wash",
    rating: 4,
    category: "women",
    categoryNo: 5,
    productId: 10,
    bought: 1000,
  },
  {
    name: "",
    newPrice: 0,
    oldPrice: 0,
    description: "",
    rating: 4,
    category: "-",
    bought: 0,
  },
];

export default data;
